apiVersion: v1
kind: Service
metadata:
  name: {{ include "shoutout.fullname" . }}-app
  labels:
    {{- include "shoutout.labels" (dict "ctx" $ "component" "app") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
  selector:
    {{- include "shoutout.selectorLabels" (dict "ctx" $ "component" "app") | nindent 4 }}
